# This playbook installs development software and related packages.
---
- name: Install essential packages and related packages
  become: yes
  package: pkg={{ item }} state=present
  with_items:
    - VirtualBox
    - virtualbox-guest-additions
    - kernel-devel
    - java
    - java-devel